### ISSUE TITLE
iOS13 iPad显示错误

### ISSUE THREAD

**Issue by LustySwimmer** [cntrump/SFSplitViewController#1]
首先非常感谢作者提供的实现思路，这个demo在iOS13以下表现是正常的，在iOS13上iPad竖屏默认显示的是detail而不是master，也就是只要竖屏就只能看到占位控制器，而且UISplitViewControllerDelegate的回调方法只有func splitViewController(_ svc: UISplitViewController, willChangeTo displayMode: UISplitViewController.DisplayMode)会走，而且displayMode是primaryOverlay

**Comment by cntrump** [comment]
fixed.
